### ISSUE TITLE
no license

### ISSUE THREAD

**Issue by x37v** [remusao/Bison-Flex-CPP-template#1]
Would be great if you could add a license so that folks can for your project and use it as the base for their own.

**Comment by remusao** [comment]
Thanks for the suggestion, I will look into it.

**Comment by remusao** [comment]
@x37v I added an MIT license: 818ebc448656e2bb6b18d9e89b0228f5ba8f8cc9
I hope this works for you.

**Comment by x37v** [comment]
@remusao that is fantastic! Thank you. I hope that the work I use your template for will eventually be useful for [pure data](https://puredata.info/) and MIT derived work should be compatible with that project.

**Comment by remusao** [comment]
@x37v I'm very happy that you find this template useful! Let me know if I can help in any way, the project looks really interesting.

**Comment by x37v** [comment]
@remusao Thank you!
I spent a while trying to roll my own, I found the documentation for bison to be a bit obtuse, but your project got me to a starting off point very quickly after I found it. I'll certainly send pull requests if I make any changes that seem like they'd benefit the base project.

**Comment by x37v** [comment]
@remusao hey, I posted the project that I used your parser template for: https://github.com/x37v/jit-expr
.. in case you're interested in checking it out.
